showNewVersionIcon: false
hideAfterStartup: true
randomControllerPort: true
runTimeFormat: 'hh : mm : ss'
trayOrders:
  - - icon
  - - status
    - traffic
    - text
hideTrayIcon: false
connShowProcess: true
showTrayProxyDelayIndicator: true
connMode: true
connProfile: true
connProxy: 0
latencyTimeout: .nan
fontFamily: ''
proxyOrder: 0
proxyDelayType: 1
latencyUrl: http://www.apple.com/library/test/success.html
theme: 0
mixinText: |
  # Mixin é…ç½®ï¼ˆè¦†ç›–é…ç½®ï¼‰
  # Authorï¼šLyana-nullptr (shabbyacc@outlook.com)
  # Last Editï¼š2025-02-06
  # Noteï¼šæ¨èä¸ºæœ¬é…ç½®ä½¿ç”¨ LF æ¢è¡Œæ ¼å¼
  mixin:
    # è¦†ç›– DNS é…ç½®
    dns:
      enable: true
      ipv6: true

      # å¢å¼ºæ¨¡å¼ï¼Œæ¨èä½¿ç”¨ fake-ip
      enhanced-mode: fake-ip
      # fake-ip æ¨¡å¼ä½¿ç”¨çš„åœ°å€æ± 
      fake-ip-range: 198.18.0.1/16
      # fake-ip æ’é™¤åˆ—è¡¨ï¼Œæ”¯æŒé€šé…ç¬¦
      # è®¾ç½®äº†é€šé…ç¬¦çš„åŸŸåå¿…é¡»ä½¿ç”¨å¼•å·åŒ…è£¹
      # é€šé…ç¬¦ï¼š
      #   - `*.` åŒ¹é…å•çº§å­åŸŸåï¼š'*.qq.com' åŒ¹é… a.qq.comï¼Œä¸åŒ¹é… qq.com
      #   - `.` åŒ¹é…å¤šçº§å­åŸŸåï¼š'.qq.com' åŒ¹é… a.qq.com å’Œ a.b.qq.comï¼Œä¸åŒ¹é… qq.com
      #   - `+.` åŒ¹é…å¤šçº§å­åŸŸåå’Œè‡ªèº«ï¼š'+.qq.com' åŒ¹é… a.qq.comã€a.b.qq.com å’Œ qq.com
      fake-ip-filter:
        # Local & Internal
        - '*.lan'
        - '*.local'
        - '*.docker.internal'
        - WORKGROUP
        # Connect Test
        - '*.msftncsi.com'
        - '*.msftconnecttest.com'
        # NTP
        - 'ntp.ntsc.ac.cn'
        - '*.ntp.org.cn'
        - 'ntp.*.edu.cn'
        - 'time.*.edu.cn'
        - '+.pool.ntp.org'
        - 'ntp.*.com'
        - 'ntp1.*.com'
        - 'ntp2.*.com'
        - 'ntp3.*.com'
        - 'ntp4.*.com'
        - 'ntp5.*.com'
        - 'ntp6.*.com'
        - 'ntp7.*.com'
        - 'time.*.com'
        - 'time1.*.com'
        - 'time2.*.com'
        - 'time3.*.com'
        - 'time4.*.com'
        - 'time5.*.com'
        - 'time6.*.com'
        - 'time7.*.com'
        # Social Media
        - localhost.ptlogin2.qq.com
        # Music
        - '*.y.qq.com'
        - '*.music.tc.qq.com'
        - aqqmusic.tc.qq.com
        - '*.stream.qqmusic.qq.com'
        - '*.music.163.com'
        - '*.126.net'
        - songsearch.kugou.com
        - trackercdn.kugou.com
        - '*.kuwo.cn'
        - musicapi.taihe.com
        - music.taihe.com
        # Game
        - 'xbox.*.*.microsoft.com'
        - '*.*.xboxlive.com'
        - '*.n.n.srv.nintendo.net'
        - '*.stun.playstation.net'
        # STUN Server
        - '+.stun.*.*'
        - '+.stun.*.*.*'
        - '+.stun.*.*.*.*'
        - '+.stun.*.*.*.*.*'
        - '+.stun01.*.*'
        - 'stunserver.*'
        - 'stunserver.*.*'

      # default-nameserver ç”¨äºè§£æ nameserver å’Œ fallback ä¸­çš„ DNS æœåŠ¡å™¨
      # å› æ­¤å¿…é¡»æŒ‡å®š IPï¼Œæ”¯æŒ UDPã€TCPã€DoTã€DoH
      # Clash æ€»æ˜¯ä½¿ç”¨ç¬¬ä¸€ä¸ªç»“æœï¼Œé€‚å½“è®¾ç½®å‡ ä¸ªå“åº”å¿«çš„ DNS æœåŠ¡å™¨å³å¯
      # default-nameserver:
      #   - '223.5.5.5' # é˜¿é‡Œ IPv4
      #   - '119.29.29.29' # è…¾è®¯ IPv4
      #   - '[2400:3200::1]:53' # é˜¿é‡Œ IPv6
      #   - '[2402:4e00::]:53' # è…¾è®¯ IPv6
      # nameserver æ”¯æŒ UDPã€TCPã€DoTã€DoH
      nameserver:
        - '223.5.5.5' # é˜¿é‡Œ IPv4
        - '119.29.29.29' # è…¾è®¯ IPv4
        - '[2400:3200::1]:53' # é˜¿é‡Œ IPv6
        - '[2402:4e00::]:53' # è…¾è®¯ IPv6
      # fallback å¯ä»¥æŒ‡å®š IP æˆ–åŸŸåï¼ŒåŒæ ·æ”¯æŒ UDPã€TCPã€DoTã€DoH
      # é…ç½® fallback åé»˜è®¤å¯ç”¨ fallback-filter, geoip-code é»˜è®¤ä¸º CN
      fallback:
        - https://223.5.5.5/dns-query # é˜¿é‡Œ DoH, ECS Support
        - https://1.1.1.1/dns-query # Cloudflare DoH
        - https://8.8.8.8/dns-query # Google DoH
        - tls://223.5.5.5:853 # é˜¿é‡Œ DoT, ECS Support
        - tls://1.1.1.1:853 # Cloudflare DoT
        - tls://8.8.8.8:853 # Google DoT
      # fallback-filter ä¼šå¯¹ IP è¿›è¡Œè¿‡æ»¤ï¼Œæ˜¯å¯¹æŠ— DNS æ±¡æŸ“æ”»å‡»çš„ä¸€ç§æªæ–½
      # 1. å½“ geoip å¼€å¯ä¸” code è®¾ç½®ä¸º CN æ—¶
      # å±äºä¸­å›½çš„ IP å°†ä½¿ç”¨ nameserver ä¸­çš„ dns
      # å…¶å®ƒå›½å®¶çš„ IP å°†ä½¿ç”¨ fallback ä¸­çš„ dns
      # 2. å½“è¯·æ±‚çš„åŸŸååŒ¹é… domain ä¸” dns å“åº”çš„ ip åŒ¹é… ip-cidr æ—¶
      # å¼ºåˆ¶ä½¿ç”¨ fallback ä¸­çš„ dns
      fallback-filter:
        geoip: true
        geoip-code: CN
        ip-cidr:
          - 240.0.0.0/4
        domain:
          - '+.google.com'
          - '+.facebook.com'
          - '+.twitter.com'
          - '+.youtube.com'
          - '+.xn--ngstr-lra8j.com'
          - '+.google.cn'
          - '+.googleapis.cn'
          - '+.googleapis.com'
          - '+.gvt1.com'

    # è¦†ç›– Tun é…ç½®
    tun:
      # TUN è®¾å¤‡å¯ä»¥ç”¨æ¥å¤„ç† TCPã€UDPã€ICMP æµé‡ï¼Œå°†æµé‡è½¬å‘åˆ°è™šæ‹Ÿç½‘å¡ï¼Œå®ç°ä»£ç†
      # éœ€è¦åœ¨ `General -> Service Mode` å®‰è£…æœåŠ¡
      enable: true
      # æ¨èä½¿ç”¨ systemï¼Œéœ€è¦åœ¨ `General -> Clash Core` æ·»åŠ é˜²ç«å¢™è§„åˆ™
      stack: system
      # å½“ fake-ip-range æ˜¯ 198.18.0.1/16, åº”è¯¥åŠ«æŒ 198.18.0.2:53ï¼Œè¯·å‹¿ä¿®æ”¹
      dns-hijack:
        - 198.18.0.2:53
      # è‡ªåŠ¨ç®¡ç†ç³»ç»Ÿè·¯ç”±è¡¨ï¼Œå®ç°ä»£ç†ï¼Œä»…æ¥æ”¶ IPv4 æµé‡
      auto-route: true
      # æ›´æ¨èä½¿ç”¨ interface-name æŒ‡å®šç½‘å¡åç§°
      auto-detect-interface: true
    # interface-name: 'tun0'
profileParsersText: >
  # Parsers é…ç½®ï¼ŒProfile å¤„ç†å™¨ï¼Œæ”¯æŒè®¾ç½®å¤šä¸ªï¼ˆæ•°ç»„æ ¼å¼ï¼‰

  # Author: Lyana-nullptr

  # Last Edit: 2025-02-06

  # Noteï¼šæ¨èä¸ºæœ¬é…ç½®ä½¿ç”¨ LF æ¢è¡Œæ ¼å¼

  parsers:
    # - reg: ^.*$ åŒ¹é…æ‰€æœ‰è®¢é˜…
    # - url: https://example.com/profile.yaml åŒ¹é…æŒ‡å®šè®¢é˜…
    - reg: ^.*$
      # åˆ é™¤æœåŠ¡å•†æä¾›çš„ DNSã€ç­–ç•¥ç»„ã€è§„åˆ™æä¾›è€…å’Œè§„åˆ™
      code: |
        module.exports.parse = (raw, { yaml }) => {
          const rawObj = yaml.parse(raw)
          return yaml.stringify({
            ...rawObj,
            dns: {},
            'proxy-groups': [],
            'rule-providers': [],
            rules: []
          })
        }
      # æ’å…¥è‡ªå·±çš„é…ç½®
      yaml:
        # æ’å…¥ç­–ç•¥ç»„
        # ç­–ç•¥ç»„ç¤ºä¾‹
        # - name: ç­–ç•¥ç»„å
        #   type: select / url-test / fallback / load-balance     # æ‰‹åŠ¨é€‰æ‹©/å»¶è¿Ÿæµ‹è¯•/å›é€€/è´Ÿè½½å‡è¡¡
        #   url: http://www.apple.com/library/test/success.html   # æµ‹è¯•åœ°å€
        #   interval: 60                                          # æµ‹è¯•é—´éš”ï¼ˆsï¼‰
        #   tolerance: 150                                        # å®¹å¿åº¦ï¼ˆmsï¼‰
        #   proxies:
        #       - èŠ‚ç‚¹åç§°
        #       - å…¶ä»–åˆ†ç»„çš„å¥—å¨ƒ
        prepend-proxy-groups:
          - name: ğŸ‘¾ å»é­”æ³•ä¸–ç•Œ
            type: select
            proxies:
              - ğŸ§­ å°±è¿‘åŸåˆ™
              - ğŸš¢ æƒ³å»ç¥–å›½çš„å°å²›
              - âš“ æƒ³å»åäººæ­¥è¡Œè¡—
              - â›©ï¸ æƒ³å»å²›å›½è¿˜äººæƒ…
              - ğŸ”« æƒ³å»è‡ªç”±ç¾åˆ©åš
              - ğŸ¤£ ä½ é€‰çš„å˜›å¶åƒ
          - name: ğŸ§­ å°±è¿‘åŸåˆ™
            type: url-test
            url: http://www.apple.com/library/test/success.html
            interval: 60
            tolerance: 150
          - name: ğŸš¢ æƒ³å»ç¥–å›½çš„å°å²›
            type: url-test
            url: http://www.apple.com/library/test/success.html
            interval: 180
            tolerance: 150
          - name: âš“ æƒ³å»åäººæ­¥è¡Œè¡—
            type: url-test
            url: http://www.apple.com/library/test/success.html
            interval: 180
            tolerance: 150
          - name: â›©ï¸ æƒ³å»å²›å›½è¿˜äººæƒ…
            type: url-test
            url: http://www.apple.com/library/test/success.html
            interval: 180
            tolerance: 150
          - name: ğŸ”« æƒ³å»è‡ªç”±ç¾åˆ©åš
            type: url-test
            url: http://www.apple.com/library/test/success.html
            interval: 180
            tolerance: 150
          - name: ğŸ¤£ ä½ é€‰çš„å˜›å¶åƒ
            type: select
          - name: ğŸ‘» é¬¼å±‹
            type: select
            proxies:
              - REJECT
              - DIRECT
          - name: ğŸ¦“ è¿·è·¯äº†æ€ä¹ˆæ–‘é©¬
            type: select
            proxies:
              - ğŸ‘¾ å»é­”æ³•ä¸–ç•Œ
              - DIRECT
        # ç”¨å‘½ä»¤é¢„å¤„ç†ç­–ç•¥ç»„
        commands:
          # ä¸€äº›å¯èƒ½ç”¨åˆ°çš„æ­£åˆ™è¿‡æ»¤èŠ‚ç‚¹ç¤ºä¾‹ï¼Œä½¿åˆ†ç»„æ›´ç»†è‡´
          # []proxyNames|a                         # åŒ…å«a
          # []proxyNames|^(.*)(a|b)+(.*)$          # åŒ…å«aæˆ–b
          # []proxyNames|^(?=.*a)(?=.*b).*$        # åŒ…å«aå’Œb
          # []proxyNames|^((?!b).)*a((?!b).)*$     # åŒ…å«aä¸”ä¸åŒ…å«b
          # []proxyNames|^((?!b|c).)*a((?!b|c).)*$ # åŒ…å«aä¸”ä¸åŒ…å«bæˆ–c
          # å‘æŒ‡å®šç­–ç•¥ç»„æ·»åŠ è®¢é˜…ä¸­ç¬¦åˆåœ°åŒºçš„èŠ‚ç‚¹
          - proxy-groups.ğŸ§­ å°±è¿‘åŸåˆ™.proxies.0+[]proxyNames
          - proxy-groups.ğŸš¢ æƒ³å»ç¥–å›½çš„å°å²›.proxies.0+[]proxyNames|^(.*)(é¦™æ¸¯|æ¾³é—¨|å°æ¹¾)+(.*)$
          - proxy-groups.âš“ æƒ³å»åäººæ­¥è¡Œè¡—.proxies.0+[]proxyNames|æ–°åŠ å¡
          - proxy-groups.â›©ï¸ æƒ³å»å²›å›½è¿˜äººæƒ….proxies.0+[]proxyNames|æ—¥æœ¬
          - proxy-groups.ğŸ”« æƒ³å»è‡ªç”±ç¾åˆ©åš.proxies.0+[]proxyNames|ç¾å›½
          - proxy-groups.ğŸ¤£ ä½ é€‰çš„å˜›å¶åƒ.proxies.0+[]proxyNames

        # æ’å…¥è§„åˆ™æä¾›è€…
        # å›½å†…ç¯å¢ƒæ¨èä½¿ç”¨ https://gcore.jsdelivr.net/ CDN åŠ é€Ÿ GitHub èµ„æº
        mix-rule-providers:
          applications:
            type: http
            behavior: classical
            url: 'https://gcore.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/applications.txt'
            path: ./ruleset/applications.yaml
            interval: 86400
          private:
            type: http
            behavior: domain
            url: 'https://gcore.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/private.txt'
            path: ./ruleset/private.yaml
            interval: 86400
          reject:
            type: http
            behavior: domain
            url: 'https://gcore.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt'
            path: ./ruleset/reject.yaml
            interval: 86400
          icloud:
            type: http
            behavior: domain
            url: 'https://gcore.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/icloud.txt'
            path: ./ruleset/icloud.yaml
            interval: 86400
          apple:
            type: http
            behavior: domain
            url: 'https://gcore.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/apple.txt'
            path: ./ruleset/apple.yaml
            interval: 86400
          google:
            type: http
            behavior: domain
            url: 'https://gcore.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/google.txt'
            path: ./ruleset/google.yaml
            interval: 86400
          proxy:
            type: http
            behavior: domain
            url: 'https://gcore.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt'
            path: ./ruleset/proxy.yaml
            interval: 86400
          direct:
            type: http
            behavior: domain
            url: 'https://gcore.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/direct.txt'
            path: ./ruleset/direct.yaml
            interval: 86400
          lancidr:
            type: http
            behavior: ipcidr
            url: 'https://gcore.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/lancidr.txt'
            path: ./ruleset/lancidr.yaml
            interval: 86400
          cncidr:
            type: http
            behavior: ipcidr
            url: 'https://gcore.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/cncidr.txt'
            path: ./ruleset/cncidr.yaml
            interval: 86400
          telegramcidr:
            type: http
            behavior: ipcidr
            url: 'https://gcore.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/telegramcidr.txt'
            path: ./ruleset/telegramcidr.yaml
            interval: 86400

        # æ’å…¥è§„åˆ™
        # è§„åˆ™ç”±ä¸Šå¾€ä¸‹åŒ¹é…ï¼Œå³ï¼šä¸Šé¢è§„åˆ™å‘½ä¸­å°±ä¸å†å¾€ä¸‹åŒ¹é…
        prepend-rules:
          # åœ¨è¿™é‡Œæ·»åŠ è‡ªå·±çš„è§„åˆ™
          # Connect Test
          - DOMAIN,www.msftconnecttest.com,ğŸ‘¾ å»é­”æ³•ä¸–ç•Œ
          - DOMAIN,www.msftncsi.com,ğŸ‘¾ å»é­”æ³•ä¸–ç•Œ
          # è®¢é˜…æœåŠ¡
          - DOMAIN,cm-sub.pz.pe,DIRECT
          # æ¸¸æˆè”æœº
          - PROCESS-NAME,ForzaHorizon4.exe,DIRECT
          # Steam ä¸‹è½½æœåŠ¡ç›´è¿ï¼Œçœæµé‡
          - DOMAIN-SUFFIX,cm.steampowered.com,DIRECT
          - DOMAIN-SUFFIX,steamserver.net,DIRECT
          # å…¶ä»–
          - DOMAIN-SUFFIX,tampermonkey.net,ğŸ‘¾ å»é­”æ³•ä¸–ç•Œ

          # Provider æ¨èçš„åŒ¹é…è§„åˆ™
          - RULE-SET,applications,DIRECT # éœ€è¦ç›´è¿çš„è¿›ç¨‹/åº”ç”¨
          - RULE-SET,private,DIRECT # éœ€è¦ç›´è¿çš„ç§æœ‰åŸŸå
          - RULE-SET,reject,ğŸ‘» é¬¼å±‹ # æ‹¦æˆªåŸŸå
          - RULE-SET,icloud,DIRECT # iCloud
          - RULE-SET,apple,DIRECT # Apple
          - RULE-SET,google,PROXY # Google
          - RULE-SET,proxy,ğŸ‘¾ å»é­”æ³•ä¸–ç•Œ # éœ€è¦ä»£ç†çš„åŸŸå
          - RULE-SET,direct,DIRECT # éœ€è¦ç›´è¿çš„åŸŸå
          - RULE-SET,lancidr,DIRECT # æœ¬åœ° IP æ± 
          - RULE-SET,cncidr,DIRECT # å›½å†… IP æ± 
          - RULE-SET,telegramcidr,ğŸ‘¾ å»é­”æ³•ä¸–ç•Œ # Telegram IP æ± 
          - GEOIP,LAN,DIRECT
          - GEOIP,CN,DIRECT
          - MATCH,ğŸ¦“ è¿·è·¯äº†æ€ä¹ˆæ–‘é©¬
editor: 1
editorFontSize: 14
showNotifications: false
titleBarText: 'Current Mode: %mode%, Mixin Status: %mixin%. (,,Â´â€¢Ï‰â€¢)ãƒ"(Â´ã£Ï‰â€¢ï½€ã€‚)'
trayProxiesStyle: 1
hideUnselectableGroup: true
showProxyFilter: true
connChainType: 2
checkForUpdates: false
childProcessText: |
  processes: # array
systemTheme: true
useModeIcons: true
