showNewVersionIcon: false
hideAfterStartup: true
randomControllerPort: true
runTimeFormat: "hh : mm : ss"
trayOrders:
  - - icon
  - - status
    - traffic
    - text
hideTrayIcon: false
connShowProcess: true
showTrayProxyDelayIndicator: true
connMode: true
connProfile: true
connProxy: 1
latencyTimeout: .nan
fontFamily: ""
proxyOrder: 0
proxyDelayType: 1
latencyUrl: http://www.apple.com/library/test/success.html
theme: 0
mixinText: "# author: Lyana-nullptr\r

  # version: 2024.10.15\r

  # Mixin é…ç½®ï¼ˆè¦†ç›–é…ç½®ï¼‰\r

  mixin:\r

  \  # DNS é…ç½®\r

  \  dns:\r

  \    enable: true\r

  \    ipv6: true\r

  \    enhanced-mode: fake-ip # æ¨èä½¿ç”¨ fake-ip æ¨¡å¼\r

  \    fake-ip-range: 198.18.0.1/16 # fake-ip ä½¿ç”¨çš„åœ°å€æ± \r

  \    # fake-ip æ’é™¤åˆ—è¡¨ï¼Œåœ¨åˆ—è¡¨ä¸­çš„åŸŸåä½¿ç”¨çœŸå® IP åœ°å€\r

  \    fake-ip-filter:\r

  \      # === Local ===\r

  \      - \"*.lan\"\r

  \      - \"*.local\"\r

  \      - \"*.docker.internal\"\r

  \      # === Microsoft Windows Service ===\r

  \      - \"*.msftncsi.com\"\r

  \      - \"*.msftconnecttest.com\"\r

  \      - WORKGROUP\r

  \      # === NTP Service ===\r

  \      - time.*.com\r

  \      - time1.*.com\r

  \      - time2.*.com\r

  \      - time3.*.com\r

  \      - time4.*.com\r

  \      - time5.*.com\r

  \      - time6.*.com\r

  \      - time7.*.com\r

  \      - time.*.gov\r

  \      - time.*.edu.cn\r

  \      - \"*.time.edu.cn\"\r

  \      - ntp.*.com\r

  \      - ntp1.*.com\r

  \      - ntp2.*.com\r

  \      - ntp3.*.com\r

  \      - ntp4.*.com\r

  \      - ntp5.*.com\r

  \      - ntp6.*.com\r

  \      - ntp7.*.com\r

  \      - ntp.*.*.cn\r

  \      - \"*.ntp.org.cn\"\r

  \      - +.pool.ntp.org\r

  \      # === Social Media Service ===\r

  \      # NetEase\r

  \      - \"*.music.163.com\"\r

  \      - \"*.126.net\"\r

  \      # Baidu\r

  \      - musicapi.taihe.com\r

  \      - music.taihe.com\r

  \      # Kugou\r

  \      - songsearch.kugou.com\r

  \      - trackercdn.kugou.com\r

  \      # Kuwo\r

  \      - \"*.kuwo.cn\"\r

  \      # JOOX\r

  \      - api-jooxtt.sanook.com\r

  \      - api.joox.com\r

  \      - joox.com\r

  \      # QQ\r

  \      - localhost.ptlogin2.qq.com\r

  \      - \"*.y.qq.com\"\r

  \      - \"*.music.tc.qq.com\"\r

  \      - aqqmusic.tc.qq.com\r

  \      - \"*.stream.qqmusic.qq.com\"\r

  \      # === Game Service ===\r

  \      # Nintendo Switch\r

  \      - \"*.n.n.srv.nintendo.net\"\r

  \      # Sony PlayStation\r

  \      - \"*.stun.playstation.net\"\r

  \      # Microsoft Xbox\r

  \      - xbox.*.*.microsoft.com\r

  \      - \"*.*.xboxlive.com\"\r

  \      # === STUN Server ===\r

  \      - +.stun.*.*\r

  \      - +.stun.*.*.*\r

  \      - +.stun.*.*.*.*\r

  \      - +.stun.*.*.*.*.*\r

  \      - +.stun01.*.*\r

  \      - stunserver.*\r

  \      # === CQUT ===\r

  \      - +.cqut.edu.cn\r

  \    # Clash æ€»æ˜¯ä½¿ç”¨ç¬¬ä¸€ä¸ª DNS æŸ¥è¯¢çš„ç»“æœï¼Œé€‚å½“è®¾ç½®å‡ ä¸ªå“åº”å¿«çš„ DNS å³å¯\r

  \    # defalut-nameserver ç”¨äºè§£æ nameserverã€fallback ä¸­çš„ DNS\r

  \    # å¿…é¡»å†™æ˜ IPï¼Œæ”¯æŒ UDPã€TCPã€DoTã€DoH\r

  \    # default-nameserver:\r

  \    #   - \"10.103.130.172\" # æ ¡å›­ç½‘å®½å¸¦ç½‘å…³\r

  \    #   - \"180.184.1.1\" # å­—èŠ‚è·³åŠ¨ IPv4\r

  \    #   - \"180.76.76.76\" # ç™¾åº¦ IPv4\r

  \    # nameserver æ”¯æŒ UDPã€TCPã€DoTã€DoH\r

  \    nameserver:\r

  \      - \"[fe80::1999:1:]:53\"\r

  \      - \"[2400:3200:baba::1]:53\" # é˜¿é‡Œ IPv6\r

  \      - \"[2402:4e00::]:53\" # è…¾è®¯ IPv6\r

  \      - \"10.103.130.172\" # æ ¡å›­ç½‘å®½å¸¦ç½‘å…³\r

  \      - \"180.184.1.1\" # å­—èŠ‚è·³åŠ¨ IPv4\r

  \      - \"180.76.76.76\" # ç™¾åº¦ IPv4\r

  \    # fallback æ”¯æŒ UDPã€TCPã€DoTã€DoH\r

  \    # é…ç½® fallback åé»˜è®¤å¯ç”¨ fallback-filter, geoip-code ä¸º cn\r

  \    fallback:\r

  \      - https://223.5.5.5/dns-query # é˜¿é‡Œ DoH, ECS Support\r

  \      - https://1.12.12.12/dns-query # è…¾è®¯ DoH\r

  \      - https://1.1.1.1/dns-query # Cloudflare DoH\r

  \      - tls://223.5.5.5:853 # é˜¿é‡Œ DoT, ECS Support\r

  \      - tls://1.12.12.12:853 # è…¾è®¯ DoT\r

  \      - tls://1.1.1.1:853 # Cloudflare DoT\r

  \    # fallback-filter ä¼šå¯¹ IP è¿›è¡Œè¿‡æ»¤ï¼Œæ˜¯å¯¹æŠ— DNS æ±¡æŸ“æ”»å‡»çš„ä¸€ç§æªæ–½\r

  \    # 1. å½“ geoip å¼€å¯ä¸” code è®¾ç½®ä¸º CN æ—¶\r

  \    # å±äºä¸­å›½çš„ IP å°†ä½¿ç”¨ nameserver ä¸­çš„ dns\r

  \    # å…¶å®ƒå›½å®¶çš„ IP å°†ä½¿ç”¨ fallback ä¸­çš„ dns\r

  \    # 2. å½“è¯·æ±‚çš„åŸŸååŒ¹é… domain ä¸” dns å“åº”çš„ ip åŒ¹é… ip-cidr\r

  \    # å¼ºåˆ¶ä½¿ç”¨ fallback ä¸­çš„ dns\r

  \    fallback-filter:\r

  \      geoip: true\r

  \      geoip-code: CN\r

  \      ip-cidr:\r

  \        - 240.0.0.0/4\r

  \      domain:\r

  \        - +.google.com\r

  \        - +.facebook.com\r

  \        - +.twitter.com\r

  \        - +.youtube.com\r

  \        - +.xn--ngstr-lra8j.com\r

  \        - +.google.cn\r

  \        - +.googleapis.cn\r

  \        - +.googleapis.com\r

  \        - +.gvt1.com\r

  \  # Tun é…ç½®ï¼ˆWindows ç‰ˆï¼‰\r

  \  tun:\r

  \    enable: true\r

  \    stack: system # ä½¿ç”¨ system stack éœ€è¦åœ¨é˜²ç«å¢™æ”¾è¡Œç¨‹åº\r

  \    # å½“ fake-ip-range æ˜¯ 198.18.0.1/16, åº”è¯¥åŠ«æŒ 198.18.0.2:53\r

  \    dns-hijack:\r

  \      - 198.18.0.2:53\r

  \    auto-route: true\r

  \    auto-detect-interface: true\r\n"
profileParsersText: "# author: Lyana-nullptr\r

  # version: 2024.10.15\r

  # é…ç½®æ–‡ä»¶è½¬æ¢å™¨ï¼Œæ•°ç»„æ ¼å¼\r

  parsers:\r

  \  # - reg: ^.*$ åŒ¹é…æ‰€æœ‰è®¢é˜…ï¼Œæˆ–  - url: https://example.com/profile.yaml æŒ‡å®šè®¢é˜…\r

  \  - reg: ^.*$\r

  \    # åˆ é™¤æœåŠ¡å•†æä¾›çš„ DNSã€ç­–ç•¥ç»„ã€è§„åˆ™æä¾›è€…å’Œè§„åˆ™\r

  \    code: |\r

  \      module.exports.parse = (raw, { yaml }) => {\r

  \        const rawObj = yaml.parse(raw)\r

  \        const dns = {}\r

  \        const proxyGroups = []\r

  \        const ruleProviders = []\r

  \        const rules = []\r

  \        return yaml.stringify({ ...rawObj, dns,'proxy-groups': proxyGroups,
  'rule-providers': ruleProviders, rules })\r

  \      }\r

  \    # å»ºç«‹è‡ªå·±çš„é…ç½®\r

  \    yaml:\r

  \      # ç­–ç•¥ç»„\r

  \      # ç­–ç•¥ç»„ç¤ºä¾‹\r

  \      # - name: åˆ†ç»„å\r

  \      #   type: select       # æ‰‹åŠ¨é€‰ç‚¹\r

  \      #   url-test           # è‡ªåŠ¨é€‰æ‹©å»¶è¿Ÿæœ€ä½çš„èŠ‚ç‚¹\r

  \      #   fallback           # èŠ‚ç‚¹æ•…éšœæ—¶è‡ªåŠ¨åˆ‡æ¢ä¸‹ä¸€ä¸ª\r

  \      #   laod-balance       # å‡è¡¡ä½¿ç”¨åˆ†ç»„å†…çš„èŠ‚ç‚¹\r

  \      #   url: http://www.apple.com/library/test/success.html         #
  æµ‹è¯•åœ°å€ éselectç±»å‹åˆ†ç»„å¿…è¦\r

  \      #   interval: 60       # è‡ªåŠ¨æµ‹è¯•é—´éš”æ—¶é—´ï¼Œå•ä½ç§’ éselectç±»å‹åˆ†ç»„ å¿…è¦\r

  \      #   tolerance: 150     # å…è®¸åå·®çš„ msï¼ŒèŠ‚ç‚¹ä¹‹é—´å»¶è¿Ÿå·®å°äºè¯¥å€¼ä¸åˆ‡æ¢ éå¿…è¦\r

  \      #   proxies:\r

  \      #       - èŠ‚ç‚¹åç§°æˆ–å…¶ä»–åˆ†ç»„å¥—å¨ƒ\r

  \      prepend-proxy-groups:\r

  \        - name: ğŸ¥° ä»£ä¹‹ä»¥ç†\r

  \          type: select\r

  \          proxies:\r

  \            - âœˆï¸ è‡ªåŠ¨é€‰æ‹©ï¼šå…¨éƒ¨\r

  \            - ğŸ è‡ªåŠ¨é€‰æ‹©ï¼šæ¸¯æ¾³å°\r

  \            - ğŸ« è‡ªåŠ¨é€‰æ‹©ï¼šæ–°åŠ å¡\r

  \            - â›©ï¸ è‡ªåŠ¨é€‰æ‹©ï¼šæ—¥æœ¬\r

  \            - ğŸ—½ è‡ªåŠ¨é€‰æ‹©ï¼šç¾å›½\r

  \            - ğŸ–ï¸ æ‰‹åŠ¨é€‰æ‹©\r

  \        - name: âœˆï¸ è‡ªåŠ¨é€‰æ‹©ï¼šå…¨éƒ¨\r

  \          type: url-test\r

  \          url: http://www.apple.com/library/test/success.html\r

  \          interval: 30\r

  \          tolerance: 100\r

  \        - name: ğŸ è‡ªåŠ¨é€‰æ‹©ï¼šæ¸¯æ¾³å°\r

  \          type: url-test\r

  \          url: http://www.apple.com/library/test/success.html\r

  \          interval: 60\r

  \          tolerance: 100\r

  \        - name: ğŸ« è‡ªåŠ¨é€‰æ‹©ï¼šæ–°åŠ å¡\r

  \          type: url-test\r

  \          url: http://www.apple.com/library/test/success.html\r

  \          interval: 60\r

  \          tolerance: 100\r

  \        - name: â›©ï¸ è‡ªåŠ¨é€‰æ‹©ï¼šæ—¥æœ¬\r

  \          type: url-test\r

  \          url: http://www.apple.com/library/test/success.html\r

  \          interval: 60\r

  \          tolerance: 100\r

  \        - name: ğŸ—½ è‡ªåŠ¨é€‰æ‹©ï¼šç¾å›½\r

  \          type: url-test\r

  \          url: http://www.apple.com/library/test/success.html\r

  \          interval: 60\r

  \          tolerance: 100\r

  \        - name: ğŸ–ï¸ æ‰‹åŠ¨é€‰æ‹©\r

  \          type: select\r

  \        - name: ğŸ“µ ç¦æ­¢é€šè¡Œ\r

  \          type: select\r

  \          proxies:\r

  \            - REJECT\r

  \            - DIRECT\r

  \      # å‘½ä»¤\r

  \      commands:\r

  \        - proxy-groups.âœˆï¸ è‡ªåŠ¨é€‰æ‹©ï¼šå…¨éƒ¨.proxies.0+[]proxyNames #
  å‘æŒ‡å®šç­–ç•¥ç»„æ·»åŠ è®¢é˜…ä¸­çš„èŠ‚ç‚¹åï¼Œå¯ä½¿ç”¨æ­£åˆ™è¿‡æ»¤\r

  \        - proxy-groups.ğŸ
  è‡ªåŠ¨é€‰æ‹©ï¼šæ¸¯æ¾³å°.proxies.0+[]proxyNames|^(.*)(é¦™æ¸¯|æ¾³é—¨|å°æ¹¾)+(.*)$\r

  \        - proxy-groups.ğŸ« è‡ªåŠ¨é€‰æ‹©ï¼šæ–°åŠ å¡.proxies.0+[]proxyNames|æ–°åŠ å¡\r

  \        - proxy-groups.â›©ï¸ è‡ªåŠ¨é€‰æ‹©ï¼šæ—¥æœ¬.proxies.0+[]proxyNames|æ—¥æœ¬\r

  \        - proxy-groups.ğŸ—½ è‡ªåŠ¨é€‰æ‹©ï¼šç¾å›½.proxies.0+[]proxyNames|ç¾å›½\r

  \        - proxy-groups.ğŸ–ï¸ æ‰‹åŠ¨é€‰æ‹©.proxies.0+[]proxyNames\r

  \        # ä¸€äº›å¯èƒ½ç”¨åˆ°çš„æ­£åˆ™è¿‡æ»¤èŠ‚ç‚¹ç¤ºä¾‹ï¼Œä½¿åˆ†ç»„æ›´ç»†è‡´\r

  \        # []proxyNames|a                         # åŒ…å«a\r

  \        # []proxyNames|^(.*)(a|b)+(.*)$          # åŒ…å«aæˆ–b\r

  \        # []proxyNames|^(?=.*a)(?=.*b).*$        # åŒ…å«aå’Œb\r

  \        # []proxyNames|^((?!b).)*a((?!b).)*$     # åŒ…å«aä¸”ä¸åŒ…å«b\r

  \        # []proxyNames|^((?!b|c).)*a((?!b|c).)*$ # åŒ…å«aä¸”ä¸åŒ…å«bæˆ–c\r

  \      # è§„åˆ™\r

  \      prepend-rules: # è§„åˆ™ç”±ä¸Šå¾€ä¸‹éå†ï¼Œå¦‚ä¸Šé¢è§„åˆ™å·²ç»å‘½ä¸­ï¼Œåˆ™ä¸å†å¾€ä¸‹å¤„ç†\r

  \        # è‡ªå®šä¹‰è§„åˆ™ï¼Œåœ¨è¿™é‡Œæ·»åŠ è‡ªå·±çš„æ–°è§„åˆ™\r

  \        - DOMAIN,www.msftconnecttest.com,ğŸ¥° ä»£ä¹‹ä»¥ç†\r

  \        - DOMAIN,www.msftncsi.com,ğŸ¥° ä»£ä¹‹ä»¥ç†\r

  \        - DOMAIN-SUFFIX,tampermonkey.net,ğŸ¥° ä»£ä¹‹ä»¥ç†\r

  \        - PROCESS-NAME,ForzaHorizon4.exe,DIRECT\r

  \        - DOMAIN,cm-sub.pz.pe,DIRECT\r

  \        - DOMAIN-SUFFIX,cm.steampowered.com,DIRECT\r

  \        - DOMAIN-SUFFIX,steamserver.net,DIRECT\r

  \        # provider çš„åŒ¹é…è§„åˆ™\r

  \        - RULE-SET,applications,DIRECT # éœ€è¦ç›´è¿çš„è¿›ç¨‹/åº”ç”¨\r

  \        - RULE-SET,private,DIRECT # éœ€è¦ç›´è¿çš„ç§æœ‰åŸŸå\r

  \        - RULE-SET,reject,ğŸ“µ ç¦æ­¢é€šè¡Œ # å¹¿å‘ŠåŸŸå\r

  \        - RULE-SET,tld-not-cn,ğŸ¥° ä»£ä¹‹ä»¥ç† # éä¸­å›½å¤§é™†ä½¿ç”¨çš„é¡¶çº§åŸŸååˆ—è¡¨\r

  \        - RULE-SET,gfw,ğŸ¥° ä»£ä¹‹ä»¥ç† # GFW æ‹¦æˆªçš„åŸŸå\r

  \        - RULE-SET,proxy,ğŸ¥° ä»£ä¹‹ä»¥ç† # éœ€è¦ä»£ç†çš„åŸŸå\r

  \        - RULE-SET,telegramcidr,ğŸ¥° ä»£ä¹‹ä»¥ç† # Telegram IP\r

  \        - GEOIP,CN,DIRECT\r

  \        - GEOIP,PRIVATE,DIRECT\r

  \        - MATCH,DIRECT # æœªå‘½ä¸­èµ°ç›´è¿\r

  \      # è§„åˆ™æä¾›è€…\r

  \      mix-rule-providers:\r

  \        applications:\r

  \          type: http\r

  \          behavior: classical\r

  \          url:
  \"https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/applications.t\
  xt\"\r

  \          path: ./ruleset/applications.yaml\r

  \          interval: 86400\r

  \        private:\r

  \          type: http\r

  \          behavior: domain\r

  \          url:
  \"https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/private.txt\"\r

  \          path: ./ruleset/private.yaml\r

  \          interval: 86400\r

  \        reject:\r

  \          type: http\r

  \          behavior: domain\r

  \          url:
  \"https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt\"\r

  \          path: ./ruleset/reject.yaml\r

  \          interval: 86400\r

  \        tld-not-cn:\r

  \          type: http\r

  \          behavior: domain\r

  \          url:
  \"https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/tld-not-cn.txt\
  \"\r

  \          path: ./ruleset/tld-not-cn.yaml\r

  \          interval: 86400\r

  \        gfw:\r

  \          type: http\r

  \          behavior: domain\r

  \          url:
  \"https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt\"\r

  \          path: ./ruleset/gfw.yaml\r

  \          interval: 86400\r

  \        proxy:\r

  \          type: http\r

  \          behavior: domain\r

  \          url:
  \"https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/proxy.txt\"\r

  \          path: ./ruleset/proxy.yaml\r

  \          interval: 86400\r

  \        telegramcidr:\r

  \          type: http\r

  \          behavior: ipcidr\r

  \          url:
  \"https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/telegramcidr.t\
  xt\"\r

  \          path: ./ruleset/telegramcidr.yaml\r

  \          interval: 86400\r\n"
editor: 1
editorFontSize: 14
showNotifications: false
titleBarText: 'Current Mode: %mode%, Mixin Status: %mixin%. (,,Â´â€¢Ï‰â€¢)ãƒ"(Â´ã£Ï‰â€¢ï½€ã€‚)'
trayProxiesStyle: 1
hideUnselectableGroup: true
showProxyFilter: true
connChainType: 2
checkForUpdates: false
childProcessText: |
  processes: # array
systemTheme: true
useModeIcons: true
